---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes emptyDir -o k8s-all.yaml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: media-tunnel
  name: media-tunnel
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: media-tunnel

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes emptyDir -o k8s-all.yaml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: ss-local
  name: ss-local
spec:
  ports:
    - name: "1080"
      port: 1080
      targetPort: 1080
  selector:
    io.kompose.service: ss-local

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes emptyDir -o k8s-all.yaml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes emptyDir -o k8s-all.yaml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: media-tunnel
  name: media-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: media-tunnel
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes emptyDir -o k8s-all.yaml
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: media-tunnel
    spec:
      containers:
        - env:
            - name: AUTOSSH_GATETIME
              value: "0"
            - name: SSH_BIND_IP
              value: 0.0.0.0
            - name: SSH_KEY_FILE
              value: /id_rsa
            - name: SSH_MODE
              value: -L
            - name: SSH_REMOTE_HOST
              value: 89.111.173.9
            - name: SSH_REMOTE_PORT
              value: "22"
            - name: SSH_REMOTE_USER
              value: root
            - name: SSH_TARGET_HOST
              value: localhost
            - name: SSH_TARGET_PORT
              value: "9000"
            - name: SSH_TUNNEL_PORT
              value: "8080"
          image: jnovack/autossh:latest
          name: media-tunnel
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: ssh-key
              mountPath: /id_rsa
              subPath: id_rsa
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: ssh-key
          secret:
            secretName: media-tunnel-ssh-key

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes emptyDir -o k8s-all.yaml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: ss-local
  name: ss-local
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ss-local
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes emptyDir -o k8s-all.yaml
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: ss-local
    spec:
      containers:
        - args:
            - ss-local
            - -s
            - 109.120.151.146
            - -p
            - "31856"
            - -k
            - L9mOiSnCSnG2Pvp0WaWSyW
            - -m
            - chacha20-ietf-poly1305
            - -b
            - 0.0.0.0
            - -l
            - "1080"
          image: shadowsocks/shadowsocks-libev
          name: ss-local
          ports:
            - containerPort: 1080
              protocol: TCP
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes emptyDir -o k8s-all.yaml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes emptyDir -o k8s-all.yaml
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: web
    spec:
      containers:
        - args:
            - sh
            - -c
            - |-
              cd /app/djangotutorial &&
                     python manage.py migrate &&
                     python manage.py runserver 0.0.0.0:8000
          envFrom:
            - configMapRef:
                name: env-dev
          image: neekookawaii/chatapp:latest
          name: web
          ports:
            - containerPort: 8000
              protocol: TCP
          workingDir: /app/djangotutorial
      restartPolicy: Always

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ilikeanime003@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx

---
apiVersion: v1
data:
  ALL_PROXY: socks5h://ss-local:1080
  DEBUG: "1"
  DJANGO_SETTINGS_MODULE: mysite.settings
  HTTPS_PROXY: socks5h://ss-local:1080
  NO_PROXY: 127.0.0.1,localhost,db,media-tunnel
  OPENAI_API_KEY: 
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: web-env-dev
  name: env-dev

