"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-eolxs6u_l@&rr(2szl(edcdu@3k5pckck%q0n=xo0%6p%1(p!*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'ivitestproject.ru', 'www.ivitestproject.ru', '127.0.0.1', 'localhost'
]

# Application definition

INSTALLED_APPS = [
    'polls.apps.PollsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.redirects',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.redirects.middleware.RedirectFallbackMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mysite.context_processors.theme_colors',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

TESTING = "test" in sys.argv or "PYTEST_VERSION" in os.environ

if not TESTING:
    INSTALLED_APPS = [
        *INSTALLED_APPS,
    ]
    MIDDLEWARE = [
        *MIDDLEWARE,
    ]

SITE_ID = 1


if sys.platform == 'darwin':
    MEDIA_BASE_URL = "127.0.0.1:8000/polls/media-proxy/"  # for ssh connetction to db
else:
    MEDIA_BASE_URL = "https://ivitestproject.ru/polls/media-proxy/"  # for ssh connetction to db

THEME_COLORS = {
    "primary": "#4A90E2",  # Soft but vibrant blue
    "secondary": "#2C3E50",  # Deep blue-gray
    "text": "#F9FAFB",  # Very light text
    "background": "#1C2731",  # Dark slate background
    "button": "#4A90E2",  # Reuse primary
    "button_hover": "#357ABD",  # Darker blue for hover
    "input_background": "#2F3E4D",  # Subtle input bg
    "input_border": "#5A6B7A",  # Soft neutral border
    "input_text": "#FFFFFF",  # White text in input
    "link": "#79B8FF",  # Bright accent blue
    "link_hover": "#58A6FF",  # Hover slightly darker
    "error": "#FF6B6B",  # Coral red
    "success": "#2ECC71",  # Green
    "warning": "#F39C12",  # Orange
    "info": "#9B59B6",  # Purple
    "label": "#B0BEC5",  # Light muted for secondary labels
}

DATABASES["media"] = {
    "ENGINE": "django.db.backends.postgresql",
    "NAME": "media_db",
    "USER": "media_app",
    "PASSWORD": "supersecret",
    "HOST": "79.174.85.94",
    "PORT": "5432",
}

DATABASE_ROUTERS = ["polls.db_router.MediaRouter"]
